version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: data
    volumes:
      - /data:/var/lib/postgresql/data
    entrypoint: sh -c "chmod 0700 /var/lib/postgresql/data && docker-entrypoint.sh postgres"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  data_aggregation:
    depends_on:
      - kafka
    build:
      context: ./DataAggregation
      dockerfile: Dockerfile
  data_collection:
    depends_on: 
      - kafka
    build:
      context: ./DataCollection
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "80:80"